### ISSUE TITLE
Unusable without internet D: Very bad issue

### ISSUE THREAD

**Issue by Danik32** [XNBlank/AstroSound#7]
When you dont have internet enabled all icons turn into shit.
![astrosound_2016-07-07_15-10-38](https://cloud.githubusercontent.com/assets/19243585/16652770/6fcf9c7a-4455-11e6-87a0-53363d9647ac.png)

**Comment by Danik32** [comment]
I think its because icons are imported from internet.
I guess, electron downloads + packages the ccs and js, but not icons.

**Comment by Danik32** [comment]
A solution would be downloading the icons and using local imports.
Which btw, work very strange for me.

**Comment by XNBlank** [comment]
Fixed with https://github.com/XNBlank/AstroSound-Redux/releases/tag/0.0.5-3
